# Generated by Django 4.0.2 on 2022-02-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolanding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
